tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "openssl@1.1"
brew "readline"
brew "asdf"
brew "webp"
brew "ffmpeg"
brew "fish"
brew "ghq"
brew "gifsicle"
brew "gnupg"
brew "imagemagick"
brew "jq"
brew "mas"
brew "mkcert"
brew "nkf"
brew "postgresql", restart_service: true
brew "rcm"
brew "redis", restart_service: true
brew "wget"
brew "yarn"
brew "zstd"
brew "heroku/brew/heroku"
cask "amazon-workspaces"
cask "docker"
cask "flutter"
cask "google-chrome"
cask "google-japanese-ime"
cask "haptic-touch-bar"
cask "visual-studio-code"
cask "zoom"
mas "1Password 7", id: 1333542190
mas "Magnet", id: 441258766
mas "Xcode", id: 497799835
