tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "supabase/tap"
brew "asdf"
brew "direnv"
brew "fish"
brew "ghq"
brew "gnupg"
brew "mkcert"
brew "neovim"
brew "postgresql", restart_service: true
brew "rcm"
brew "redis", restart_service: true
brew "starship"
brew "zstd"
brew "heroku/brew/heroku"
brew "supabase/tap/supabase"
cask "1password"
cask "discord"
cask "docker"
cask "google-chrome"
cask "google-japanese-ime"
cask "slack"
cask "visual-studio-code"
cask "zoom"
