tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "webp"
brew "asdf"
brew "fish"
brew "ghq"
brew "gnupg"
brew "imagemagick"
brew "mkcert"
brew "postgresql", restart_service: true
brew "rcm"
brew "redis", restart_service: true
brew "wget"
brew "zstd"
brew "heroku/brew/heroku"
cask "1password"
cask "android-studio"
cask "discord"
cask "docker"
cask "flutter"
cask "google-chrome"
cask "google-japanese-ime"
cask "slack"
cask "visual-studio-code"
cask "zoom"
