# Bundler
alias ba='bundle add'
alias be='bundle exec'
alias bi='bundle install'
alias bout='bundle outdated'
alias bu='bundle update'

# Homebrew
alias bubu='brew update && brew outdated && brew upgrade && brew cleanup'

# Docker Compose
alias dcb='docker compose build'
alias dcdn='docker compose down'
alias dco='docker compose'
alias dcps='docker compose ps'
alias dcr='docker compose run'
alias dcrm='docker compose rm'
alias dcstop='docker compose stop'
alias dcup='docker compose up'
alias dcupd='docker compose up -d'

# Git
alias ga='git add'
alias gau='git add --update'
alias gb='git branch'
alias gbD='git branch -D'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gc='git commit -v'
alias 'gc!'='git commit -v --amend'
alias gca='git commit -v -a'
alias 'gca!'='git commit -v -a --amend'
alias gcam='git commit -a -m'
alias gcb='git checkout -b'
alias gcd='git checkout develop'
alias gcm='git checkout main'
alias gcmsg='git commit -m'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcpc='git cherry-pick --continue'
alias gd='git diff'
alias gdca='git diff --cached'
alias gl='git pull'
alias glg='git log --stat'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gr='git remote'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase -i'
alias grbm='git rebase main'
alias grbs='git rebase --skip'
alias grev='git revert'
alias grh='git reset'
alias grhh='git reset --hard'
alias gsh='git show'
alias gst='git status'
alias gstall='git stash --all'
alias gstc='git stash clear'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gstu='git stash --include-untracked'

# Rails
alias rc='rails console'
alias rcs='rails console --sandbox'
alias rd='rails destroy'
alias rdb='rails dbconsole'
alias rdc='rails db:create'
alias rdd='rails db:drop'
alias rdm='rails db:migrate'
alias rdms='rails db:migrate:status'
alias rdmtc='rails db:migrate db:test:clone'
alias rdr='rails db:rollback'
alias rdrs='rails db:reset'
alias rds='rails db:seed'
alias rdsl='rails db:schema:load'
alias rdtc='rails db:test:clone'
alias rdtp='rails db:test:prepare'
alias rgen='rails generate'
alias rgm='rails generate migration'
alias rlc='rails log:clear'
alias rmd='rails middleware'
alias rn='rails notes'
alias rp='rails plugin'
alias rr='rails routes'
alias rrg='rails routes | grep'
alias rs='rails server'
alias rsd='rails server --debugger'
alias rsp='rails server --port'
alias rsts='rails stats'
alias rt='rails test'
alias ru='rails runner'
