abbr -a -- ba 'bundle add'
abbr -a -- be 'bundle exec'
abbr -a -- bi 'bundle install'
abbr -a -- bout 'bundle outdated'
abbr -a -- bu 'bundle update'
abbr -a -- bubu 'brew update && brew outdated && brew upgrade && brew cleanup'
abbr -a -- dcb 'docker compose build'
abbr -a -- dcdn 'docker compose down'
abbr -a -- dco 'docker compose'
abbr -a -- dcps 'docker compose ps'
abbr -a -- dcr 'docker compose run'
abbr -a -- dcrm 'docker compose rm'
abbr -a -- dcstop 'docker compose stop'
abbr -a -- dcup 'docker compose up'
abbr -a -- dcupd 'docker compose up -d'
abbr -a -- ga 'git add'
abbr -a -- gau 'git add --update'
abbr -a -- gb 'git branch'
abbr -a -- gbD 'git branch -D'
abbr -a -- gba 'git branch -a'
abbr -a -- gbd 'git branch -d'
abbr -a -- gc 'git commit -v'
abbr -a -- gc! 'git commit -v --amend'
abbr -a -- gca 'git commit -v -a'
abbr -a -- gca! 'git commit -v -a --amend'
abbr -a -- gcam 'git commit -a -m'
abbr -a -- gcb 'git checkout -b'
abbr -a -- gcd 'git checkout develop'
abbr -a -- gcm 'git checkout main'
abbr -a -- gcmsg 'git commit -m'
abbr -a -- gco 'git checkout'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gcpa 'git cherry-pick --abort'
abbr -a -- gcpc 'git cherry-pick --continue'
abbr -a -- gd 'git diff'
abbr -a -- gdca 'git diff --cached'
abbr -a -- gl 'git pull'
abbr -a -- glg 'git log --stat'
abbr -a -- gp 'git push'
abbr -a -- gpf 'git push --force-with-lease'
abbr -a -- gr 'git remote'
abbr -a -- grb 'git rebase'
abbr -a -- grba 'git rebase --abort'
abbr -a -- grbc 'git rebase --continue'
abbr -a -- grbi 'git rebase -i'
abbr -a -- grbm 'git rebase main'
abbr -a -- grbs 'git rebase --skip'
abbr -a -- grev 'git revert'
abbr -a -- grh 'git reset'
abbr -a -- grhh 'git reset --hard'
abbr -a -- gsh 'git show'
abbr -a -- gst 'git status'
abbr -a -- gstall 'git stash --all'
abbr -a -- gstc 'git stash clear'
abbr -a -- gstl 'git stash list'
abbr -a -- gstp 'git stash pop'
abbr -a -- gstu 'git stash --include-untracked'
abbr -a -- rc 'rails console'
abbr -a -- rcs 'rails console --sandbox'
abbr -a -- rd 'rails destroy'
abbr -a -- rdb 'rails dbconsole'
abbr -a -- rdc 'rails db:create'
abbr -a -- rdd 'rails db:drop'
abbr -a -- rdm 'rails db:migrate'
abbr -a -- rdms 'rails db:migrate:status'
abbr -a -- rdmtc 'rails db:migrate db:test:clone'
abbr -a -- rdr 'rails db:rollback'
abbr -a -- rdrs 'rails db:reset'
abbr -a -- rds 'rails db:seed'
abbr -a -- rdsl 'rails db:schema:load'
abbr -a -- rdtc 'rails db:test:clone'
abbr -a -- rdtp 'rails db:test:prepare'
abbr -a -- rgen 'rails generate'
abbr -a -- rgm 'rails generate migration'
abbr -a -- rlc 'rails log:clear'
abbr -a -- rmd 'rails middleware'
abbr -a -- rn 'rails notes'
abbr -a -- rp 'rails plugin'
abbr -a -- rr 'rails routes'
abbr -a -- rrg 'rails routes | grep'
abbr -a -- rs 'rails server'
abbr -a -- rsd 'rails server --debugger'
abbr -a -- rsp 'rails server --port'
abbr -a -- rsts 'rails stats'
abbr -a -- rt 'rails test'
abbr -a -- ru 'rails runner'
abbr -a -- vim nvim
abbr -a -- vsc code

if status is-interactive
    source /opt/homebrew/opt/asdf/libexec/asdf.fish
    direnv hook fish | source
    starship init fish | source
end
