source (brew --prefix asdf)/libexec/asdf.fish
direnv hook fish | source
starship init fish | source

if status is-interactive
    # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/brew

    abbr --add --global brewp 'brew pin'
    abbr --add --global brews 'brew list -1'
    abbr --add --global brewsp 'brew list --pinned'
    abbr --add --global bubo 'brew update && brew outdated'
    abbr --add --global bubc 'brew upgrade && brew cleanup'
    abbr --add --global bubu 'brew update && brew outdated && brew upgrade && brew cleanup'
    abbr --add --global buf 'brew upgrade --formula'
    abbr --add --global bcubo 'brew update && brew outdated --cask'
    abbr --add --global bcubc 'brew cask reinstall (brew outdated --cask) && brew cleanup'

    # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/bundler

    abbr --add --global ba 'bundle add'
    abbr --add --global bck 'bundle check'
    abbr --add --global bcn 'bundle clean'
    abbr --add --global be 'bundle exec'
    abbr --add --global bi 'bundle install'
    abbr --add --global bl 'bundle list'
    abbr --add --global bo 'bundle open'
    abbr --add --global bout 'bundle outdated'
    abbr --add --global bp 'bundle package'
    abbr --add --global bu 'bundle update'

    # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/docker-compose

    abbr --add --global dco 'docker compose'
    abbr --add --global dcb 'docker compose build'
    abbr --add --global dce 'docker compose exec'
    abbr --add --global dcps 'docker compose ps'
    abbr --add --global dcrestart 'docker compose restart'
    abbr --add --global dcrm 'docker compose rm'
    abbr --add --global dcr 'docker compose run'
    abbr --add --global dcstop 'docker compose stop'
    abbr --add --global dcup 'docker compose up'
    abbr --add --global dcupd 'docker compose up -d'
    abbr --add --global dcdn 'docker compose down'
    abbr --add --global dcl 'docker compose logs'
    abbr --add --global dclf 'docker compose logs -f'
    abbr --add --global dcpull 'docker compose pull'
    abbr --add --global dcstart 'docker compose start'
    abbr --add --global dck 'docker compose kill'

    # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git

    abbr --add --global g 'git'
    abbr --add --global ga 'git add'
    abbr --add --global gaa 'git add --all'
    abbr --add --global gapa 'git add --patch'
    abbr --add --global gau 'git add --update'
    abbr --add --global gav 'git add --verbose'
    abbr --add --global gap 'git apply'
    abbr --add --global gapt 'git apply --3way'
    abbr --add --global gb 'git branch'
    abbr --add --global gba 'git branch -a'
    abbr --add --global gbd 'git branch -d'
    abbr --add --global gbda 'git branch --no-color --merged | command grep -vE "^(+|*|\s*($(git_main_branch)|development|develop|devel|dev)\s*$)" | command xargs -n 1 git branch -d'
    abbr --add --global gbD 'git branch -D'
    abbr --add --global gbl 'git blame -b -w'
    abbr --add --global gbnm 'git branch --no-merged'
    abbr --add --global gbr 'git branch --remote'
    abbr --add --global gbs 'git bisect'
    abbr --add --global gbsb 'git bisect bad'
    abbr --add --global gbsg 'git bisect good'
    abbr --add --global gbsr 'git bisect reset'
    abbr --add --global gbss 'git bisect start'
    abbr --add --global gc 'git commit -v'
    abbr --add --global gc! 'git commit -v --amend'
    abbr --add --global gcn! 'git commit -v --no-edit --amend'
    abbr --add --global gca 'git commit -v -a'
    abbr --add --global gca! 'git commit -v -a --amend'
    abbr --add --global gcan! 'git commit -v -a --no-edit --amend'
    abbr --add --global gcans! 'git commit -v -a -s --no-edit --amend'
    abbr --add --global gcam 'git commit -a -m'
    abbr --add --global gcsm 'git commit -s -m'
    abbr --add --global gcb 'git checkout -b'
    abbr --add --global gcf 'git config --list'
    abbr --add --global gcl 'git clone --recurse-submodules'
    abbr --add --global gclean 'git clean -id'
    abbr --add --global gpristine 'git reset --hard && git clean -dffx'
    abbr --add --global gcm 'git checkout (git_main_branch)'
    abbr --add --global gcd 'git checkout develop'
    abbr --add --global gcmsg 'git commit -m'
    abbr --add --global gco 'git checkout'
    abbr --add --global gcount 'git shortlog -sn'
    abbr --add --global gcp 'git cherry-pick'
    abbr --add --global gcpa 'git cherry-pick --abort'
    abbr --add --global gcpc 'git cherry-pick --continue'
    abbr --add --global gcs 'git commit -S'
    abbr --add --global gd 'git diff'
    abbr --add --global gdca 'git diff --cached'
    abbr --add --global gdcw 'git diff --cached --word-diff'
    abbr --add --global gdct 'git describe --tags (git rev-list --tags --max-count=1)'
    abbr --add --global gds 'git diff --staged'
    abbr --add --global gdt 'git diff-tree --no-commit-id --name-only -r'
    abbr --add --global gdnolock 'git diff $@ ":(exclude)package-lock.json" ":(exclude)*.lock"'
    abbr --add --global gdv 'git diff -w $@ | view -'
    abbr --add --global gdw 'git diff --word-diff'
    abbr --add --global gf 'git fetch'
    abbr --add --global gfa 'git fetch --all --prune'
    abbr --add --global gfg 'git ls-files | grep'
    abbr --add --global gfo 'git fetch origin'
    abbr --add --global gg 'git gui citool'
    abbr --add --global gga 'git gui citool --amend'
    abbr --add --global ggf 'git push --force origin (git_current_branch)'
    abbr --add --global ggfl 'git push --force-with-lease origin (git_current_branch)'
    abbr --add --global ggl 'git pull origin (git_current_branch)'
    abbr --add --global ggp 'git push origin (git_current_branch)'
    abbr --add --global ggpnp 'ggl && ggp'
    abbr --add --global ggpull 'git pull origin "(git_current_branch)"'
    abbr --add --global ggpur 'ggu'
    abbr --add --global ggpush 'git push origin "(git_current_branch)"'
    abbr --add --global ggsup 'git branch --set-upstream-to=origin/(git_current_branch)'
    abbr --add --global ggu 'git pull --rebase origin (git_current_branch)'
    abbr --add --global gpsup 'git push --set-upstream origin (git_current_branch)'
    abbr --add --global ghh 'git help'
    abbr --add --global gignore 'git update-index --assume-unchanged'
    abbr --add --global gignored 'git ls-files -v | grep "^[[:lower:]]"'
    abbr --add --global git-svn-dcommit-push 'git svn dcommit && git push github (git_main_branch):svntrunk'
    abbr --add --global gk 'gitk --all --branches'
    abbr --add --global gke 'gitk --all (git log -g --pretty=%h)'
    abbr --add --global gl 'git pull'
    abbr --add --global glg 'git log --stat'
    abbr --add --global glgp 'git log --stat -p'
    abbr --add --global glgg 'git log --graph'
    abbr --add --global glgga 'git log --graph --decorate --all'
    abbr --add --global glgm 'git log --graph --max-count=10'
    abbr --add --global glo 'git log --oneline --decorate'
    abbr --add --global glol "git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
    abbr --add --global glols "git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --stat"
    abbr --add --global glod "git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'"
    abbr --add --global glods "git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset' --date=short"
    abbr --add --global glola "git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --all"
    abbr --add --global glog 'git log --oneline --decorate --graph'
    abbr --add --global gloga 'git log --oneline --decorate --graph --all'
    abbr --add --global glp 'git log --pretty=<format>'
    abbr --add --global gm 'git merge'
    abbr --add --global gmom 'git merge origin/(git_main_branch)'
    abbr --add --global gmt 'git mergetool --no-prompt'
    abbr --add --global gmtvim 'git mergetool --no-prompt --tool=vimdiff'
    abbr --add --global gmum 'git merge upstream/(git_main_branch)'
    abbr --add --global gma 'git merge --abort'
    abbr --add --global gp 'git push'
    abbr --add --global gpd 'git push --dry-run'
    abbr --add --global gpf 'git push --force-with-lease'
    abbr --add --global gpf! 'git push --force'
    abbr --add --global gpoat 'git push origin --all && git push origin --tags'
    abbr --add --global gpu 'git push upstream'
    abbr --add --global gpv 'git push -v'
    abbr --add --global gr 'git remote'
    abbr --add --global gra 'git remote add'
    abbr --add --global grb 'git rebase'
    abbr --add --global grba 'git rebase --abort'
    abbr --add --global grbc 'git rebase --continue'
    abbr --add --global grbd 'git rebase develop'
    abbr --add --global grbi 'git rebase -i'
    abbr --add --global grbm 'git rebase (git_main_branch)'
    abbr --add --global grbs 'git rebase --skip'
    abbr --add --global grev 'git revert'
    abbr --add --global grh 'git reset'
    abbr --add --global grhh 'git reset --hard'
    abbr --add --global groh 'git reset origin/(git_current_branch) --hard'
    abbr --add --global grm 'git rm'
    abbr --add --global grmc 'git rm --cached'
    abbr --add --global grmv 'git remote rename'
    abbr --add --global grrm 'git remote remove'
    abbr --add --global grs 'git restore'
    abbr --add --global grset 'git remote set-url'
    abbr --add --global grss 'git restore --source'
    abbr --add --global grt 'cd (git rev-parse --show-toplevel || echo .)'
    abbr --add --global gru 'git reset --'
    abbr --add --global grup 'git remote update'
    abbr --add --global grv 'git remote -v'
    abbr --add --global gsb 'git status -sb'
    abbr --add --global gsd 'git svn dcommit'
    abbr --add --global gsh 'git show'
    abbr --add --global gsi 'git submodule init'
    abbr --add --global gsps 'git show --pretty=short --show-signature'
    abbr --add --global gsr 'git svn rebase'
    abbr --add --global gss 'git status -s'
    abbr --add --global gst 'git status'
    abbr --add --global gsta 'git stash push'
    abbr --add --global gsta 'git stash save'
    abbr --add --global gstaa 'git stash apply'
    abbr --add --global gstc 'git stash clear'
    abbr --add --global gstd 'git stash drop'
    abbr --add --global gstl 'git stash list'
    abbr --add --global gstp 'git stash pop'
    abbr --add --global gsts 'git stash show --text'
    abbr --add --global gstu 'git stash --include-untracked'
    abbr --add --global gstall 'git stash --all'
    abbr --add --global gsu 'git submodule update'
    abbr --add --global gsw 'git switch'
    abbr --add --global gswc 'git switch -c'
    abbr --add --global gts 'git tag -s'
    abbr --add --global gtv 'git tag | sort -V'
    abbr --add --global gtl 'gtl(){ git tag --sort=-v:refname -n -l ${1}* }; noglob gtl'
    abbr --add --global gunignore 'git update-index --no-assume-unchanged'
    abbr --add --global gunwip 'git log -n 1 | grep -q -c "--wip--" && git reset HEAD~1'
    abbr --add --global gup 'git pull --rebase'
    abbr --add --global gupv 'git pull --rebase -v'
    abbr --add --global gupa 'git pull --rebase --autostash'
    abbr --add --global gupav 'git pull --rebase --autostash -v'
    abbr --add --global glum 'git pull upstream (git_main_branch)'
    abbr --add --global gwch 'git whatchanged -p --abbrev-commit --pretty=medium'
    abbr --add --global gwip 'git add -A; git rm (git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign -m "--wip-- [skip ci]"'
    abbr --add --global gam 'git am'
    abbr --add --global gamc 'git am --continue'
    abbr --add --global gams 'git am --skip'
    abbr --add --global gama 'git am --abort'
    abbr --add --global gamscp 'git am --show-current-patch'

    # https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/npm/npm.plugin.zsh

    abbr --add --global npmg 'npm i -g'
    abbr --add --global npmS 'npm i -S'
    abbr --add --global npmD 'npm i -D'
    abbr --add --global npmF 'npm i -f'
    abbr --add --global npmE 'PATH=(npm bin):"$PATH"'
    abbr --add --global npmO 'npm outdated'
    abbr --add --global npmU 'npm update'
    abbr --add --global npmV 'npm -v'
    abbr --add --global npmL 'npm list'
    abbr --add --global npmL0 'npm ls --depth 0'
    abbr --add --global npmst 'npm start'
    abbr --add --global npmt 'npm test'
    abbr --add --global npmR 'npm run'
    abbr --add --global npmP 'npm publish'
    abbr --add --global npmI 'npm init'
    abbr --add --global npmi 'npm info'
    abbr --add --global npmSe 'npm search'

    # https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/rails

    abbr --add --global rc 'bin/rails console'
    abbr --add --global rcs 'bin/rails console --sandbox'
    abbr --add --global rd 'bin/rails destroy'
    abbr --add --global rdb 'bin/rails dbconsole'
    abbr --add --global rgen 'bin/rails generate'
    abbr --add --global rgm 'bin/rails generate migration'
    abbr --add --global rp 'bin/rails plugin'
    abbr --add --global ru 'bin/rails runner'
    abbr --add --global rs 'bin/rails server'
    abbr --add --global rsd 'bin/rails server --debugger'
    abbr --add --global rsp 'bin/rails server --port'

    abbr --add --global rdm 'bin/rails db:migrate'
    abbr --add --global rdms 'bin/rails db:migrate:status'
    abbr --add --global rdmtc 'bin/rails db:migrate db:test:clone'
    abbr --add --global rdr 'bin/rails db:rollback'
    abbr --add --global rdc 'bin/rails db:create'
    abbr --add --global rds 'bin/rails db:seed'
    abbr --add --global rdd 'bin/rails db:drop'
    abbr --add --global rdrs 'bin/rails db:reset'
    abbr --add --global rdtc 'bin/rails db:test:clone'
    abbr --add --global rdtp 'bin/rails db:test:prepare'
    abbr --add --global rdsl 'bin/rails db:schema:load'
    abbr --add --global rlc 'bin/rails log:clear'
    abbr --add --global rn 'bin/rails notes'
    abbr --add --global rr 'bin/rails routes'
    abbr --add --global rrg 'bin/rails routes | grep'
    abbr --add --global rt 'bin/rails test'
    abbr --add --global rmd 'bin/rails middleware'
    abbr --add --global rsts 'bin/rails stats'

    abbr --add --global devlog 'tail -f log/development.log'
    abbr --add --global prodlog 'tail -f log/production.log'
    abbr --add --global testlog 'tail -f log/test.log'

    abbr --add --global RED 'RAILS_ENV=development'
    abbr --add --global REP 'RAILS_ENV=production'
    abbr --add --global RET 'RAILS_ENV=test'

    # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/vscode

    abbr --add --global vsc 'code .'
    abbr --add --global vsca 'code --add'
    abbr --add --global vscd 'code --diff'
    abbr --add --global vscg 'code --goto'
    abbr --add --global vscn 'code --new-window'
    abbr --add --global vscr 'code --reuse-window'
    abbr --add --global vscw 'code --wait'
    abbr --add --global vscu 'code --user-data-dir'

    abbr --add --global vsced 'code --extensions-dir'
    abbr --add --global vscie 'code --install-extension'
    abbr --add --global vscue 'code --uninstall-extension'

    abbr --add --global vscv 'code --verbose'
    abbr --add --global vscl 'code --log'
    abbr --add --global vscde 'code --disable-extensions'
end
